[package]
name = "rocket-cache-response"
version = "0.5.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-cache-response"
homepage = "https://magiclen.org/rocket-cache-response"
keywords = ["rocket", "server", "web", "cache", "http"]
categories = ["web-programming"]
description= "This crate provides a response struct used for HTTP cache control."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/rocket-cache-response"
branch = "master"

[dependencies]
rocket = "0.4"

[dev-dependencies]
chrono = "0.4.6"