[package]
name = "rocket-cache-response"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-cache-response"
homepage = "https://magiclen.org/rocket-cache-response"
keywords = ["rocket", "server", "web", "cache", "http"]
categories = ["web-programming"]
description= "This crate provides a response struct used for HTTP cache control."
readme = "README.md"
license = "MIT"

[dependencies]
rocket = "0.3.15"